version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/portfolio
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - portfolio-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  mongodb_data: 